version: '3'
services:
  events-api:
    build: .
    command: nodemon start
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - '3000:3000'
    links:
      - mongo
    environment:
      MONGO_URL: mongodb://mongo:27017/events
      NODE_ENV: development
  mongo:
    image: mongo
    ports:
      - '27020:27017'
